In [1]:
import pandas as pd

In [2]:
data = pd.read_excel(r"C:\Users\SHRUTI S\Documents\Repos\Entab Internship\Data Analysis\June 2024.xlsx")

In [3]:
data.head()

,Ticket ID,Subject,Description,Status,Priority,Source,Type,Agent,Group,Created time,...,Happiness Index,Weightage,Module,Full name,Email,File No.,Company Name,Support,Segment,Product Type
0,991741,Registration || (Std. X) Email Format || Vince...,NaN,Closed,High,Internal,Change Request,Shivam Bhardwaj,PD- Manju,2024-05-26 09:06:59,...,NaN,1.0,Registration & Admission,1726#Elite_2,1726entab@dummy.com,1726.0,"1726#St. Vincent Pallotti School, Bengaluru, K...",Elite_2,Elite_2,MVC
1,991742,Fwd: fee payment clarification for Siya gupta ...,"Adding others. Thanks, Sourabh ---------- Forw...",Closed,High,Email,Query,Pooja Yadav,PHD,2024-05-26 10:59:36,...,NaN,NaN,Student Information,Sourabh Gupta,sourabh44@gmail.com,NaN,NaN,NaN,NaN,NaN
2,991743,Reconciliation (from 01/04/2024 to 16/05/2024)...,Reconciliation (from 01/04/2024 to 16/05/2024)...,Closed,Low,Phone,Proactive Task,Vani Poudwal,Elite_2,2024-05-26 11:02:28,...,NaN,NaN,Fee and Billing,Mr. Bhupesh Jaiswal,bhupesh@tagoreint.com,111.0,"111#Tagore International School, Vasant Vihar,...",Elite_2,Elite_2,MVC
3,991744,Fee details not uploaded,"Hi Team, My Daughter Navanya D is moving to LK...",Closed,High,Email,Query,Pooja Yadav,PHD,2024-05-26 17:48:42,...,NaN,NaN,Fee and Billing,Dinesh Dilli,ddineshnani@gmail.com,NaN,NaN,NaN,NaN,NaN
4,991745,Fwd: Double payment for the quarter March 2024...,---------- Forwarded message --------- From: D...,Closed,Low,Email,Change Request,PreetiNegi/Entab- Tech. Support,Innovators_1A,2024-05-26 19:13:02,...,NaN,NaN,Fee and Billing,Mrs. Smruti Kulkarni,powai.accounts@bombayscottish.in,562.0,"562#Bombay Scottish School, Powai, Maharashtra",Innovators_1A,Innovators_1,MVC

In [4]:
data.shape

(22708, 42)

In [5]:
data.dropna(subset=['Description'], inplace = True)

In [6]:
data.shape

(22569, 42)

In [7]:
data_for_zero = data[data['Company Name'].isnull()]

In [8]:
data_for_zero.head()

,Ticket ID,Subject,Description,Status,Priority,Source,Type,Agent,Group,Created time,...,Happiness Index,Weightage,Module,Full name,Email,File No.,Company Name,Support,Segment,Product Type
1,991742,Fwd: fee payment clarification for Siya gupta ...,"Adding others. Thanks, Sourabh ---------- Forw...",Closed,High,Email,Query,Pooja Yadav,PHD,2024-05-26 10:59:36,...,NaN,NaN,Student Information,Sourabh Gupta,sourabh44@gmail.com,NaN,NaN,NaN,NaN,NaN
3,991744,Fee details not uploaded,"Hi Team, My Daughter Navanya D is moving to LK...",Closed,High,Email,Query,Pooja Yadav,PHD,2024-05-26 17:48:42,...,NaN,NaN,Fee and Billing,Dinesh Dilli,ddineshnani@gmail.com,NaN,NaN,NaN,NaN,NaN
5,991746,Online fee payment for my younger daughter,"Dear Sir/ Madam,I want to add my younger daugh...",Closed,High,Email,Query,Pooja Yadav,PHD,2024-05-26 19:28:04,...,NaN,NaN,Other,Hardeepsingh Rawat,hardeepsinghrawat@yahoo.com,NaN,NaN,NaN,NaN,NaN
12,991753,Daily Work Dated 25-05-2024 (Client ID 1662 St...,Dear Sir Greetings of the Day! Â Work done for...,Closed,Low,Outbound Email,Query,Tanmay/Entab- Regional Coordinator,Regional Coordinators,2024-05-26 22:05:20,...,NaN,NaN,Student Information,Mukesh Deployment Saini,mukesh@entab.in,NaN,NaN,NaN,NaN,NaN
23,991765,"No coding, no problems ä¸€ automation is king",Try airSlate at no extra cost. â€Œ â€Œ â€Œ â€Œ â€Œ â€Œ â€Œ â€Œ...,Closed,High,Email,Query,Update Tracker- Pooja,Deployment,2024-05-27 06:49:22,...,NaN,NaN,Other,Sarah from pdfFiller,sarah@pdffiller.com,NaN,NaN,NaN,NaN,NaN

In [9]:
data_for_zero.shape

(4899, 42)

In [10]:
data_for_zero.head()

,Ticket ID,Subject,Description,Status,Priority,Source,Type,Agent,Group,Created time,...,Happiness Index,Weightage,Module,Full name,Email,File No.,Company Name,Support,Segment,Product Type
1,991742,Fwd: fee payment clarification for Siya gupta ...,"Adding others. Thanks, Sourabh ---------- Forw...",Closed,High,Email,Query,Pooja Yadav,PHD,2024-05-26 10:59:36,...,NaN,NaN,Student Information,Sourabh Gupta,sourabh44@gmail.com,NaN,NaN,NaN,NaN,NaN
3,991744,Fee details not uploaded,"Hi Team, My Daughter Navanya D is moving to LK...",Closed,High,Email,Query,Pooja Yadav,PHD,2024-05-26 17:48:42,...,NaN,NaN,Fee and Billing,Dinesh Dilli,ddineshnani@gmail.com,NaN,NaN,NaN,NaN,NaN
5,991746,Online fee payment for my younger daughter,"Dear Sir/ Madam,I want to add my younger daugh...",Closed,High,Email,Query,Pooja Yadav,PHD,2024-05-26 19:28:04,...,NaN,NaN,Other,Hardeepsingh Rawat,hardeepsinghrawat@yahoo.com,NaN,NaN,NaN,NaN,NaN
12,991753,Daily Work Dated 25-05-2024 (Client ID 1662 St...,Dear Sir Greetings of the Day! Â Work done for...,Closed,Low,Outbound Email,Query,Tanmay/Entab- Regional Coordinator,Regional Coordinators,2024-05-26 22:05:20,...,NaN,NaN,Student Information,Mukesh Deployment Saini,mukesh@entab.in,NaN,NaN,NaN,NaN,NaN
23,991765,"No coding, no problems ä¸€ automation is king",Try airSlate at no extra cost. â€Œ â€Œ â€Œ â€Œ â€Œ â€Œ â€Œ â€Œ...,Closed,High,Email,Query,Update Tracker- Pooja,Deployment,2024-05-27 06:49:22,...,NaN,NaN,Other,Sarah from pdfFiller,sarah@pdffiller.com,NaN,NaN,NaN,NaN,NaN

In [11]:
data_for_zero.head()

,Ticket ID,Subject,Description,Status,Priority,Source,Type,Agent,Group,Created time,...,Happiness Index,Weightage,Module,Full name,Email,File No.,Company Name,Support,Segment,Product Type
1,991742,Fwd: fee payment clarification for Siya gupta ...,"Adding others. Thanks, Sourabh ---------- Forw...",Closed,High,Email,Query,Pooja Yadav,PHD,2024-05-26 10:59:36,...,NaN,NaN,Student Information,Sourabh Gupta,sourabh44@gmail.com,NaN,NaN,NaN,NaN,NaN
3,991744,Fee details not uploaded,"Hi Team, My Daughter Navanya D is moving to LK...",Closed,High,Email,Query,Pooja Yadav,PHD,2024-05-26 17:48:42,...,NaN,NaN,Fee and Billing,Dinesh Dilli,ddineshnani@gmail.com,NaN,NaN,NaN,NaN,NaN
5,991746,Online fee payment for my younger daughter,"Dear Sir/ Madam,I want to add my younger daugh...",Closed,High,Email,Query,Pooja Yadav,PHD,2024-05-26 19:28:04,...,NaN,NaN,Other,Hardeepsingh Rawat,hardeepsinghrawat@yahoo.com,NaN,NaN,NaN,NaN,NaN
12,991753,Daily Work Dated 25-05-2024 (Client ID 1662 St...,Dear Sir Greetings of the Day! Â Work done for...,Closed,Low,Outbound Email,Query,Tanmay/Entab- Regional Coordinator,Regional Coordinators,2024-05-26 22:05:20,...,NaN,NaN,Student Information,Mukesh Deployment Saini,mukesh@entab.in,NaN,NaN,NaN,NaN,NaN
23,991765,"No coding, no problems ä¸€ automation is king",Try airSlate at no extra cost. â€Œ â€Œ â€Œ â€Œ â€Œ â€Œ â€Œ â€Œ...,Closed,High,Email,Query,Update Tracker- Pooja,Deployment,2024-05-27 06:49:22,...,NaN,NaN,Other,Sarah from pdfFiller,sarah@pdffiller.com,NaN,NaN,NaN,NaN,NaN

In [13]:
data_for_zero.to_excel(r"C:\Users\SHRUTI S\Documents\Repos\Entab Internship\Data Analysis\ZeroData.xlsx", sheet_name = 'ZeroData', index=False)

In [15]:
zeroData_forprocessing = data_for_zero[['Ticket ID', 'Description', 'Module']].copy()
zeroData_forprocessing.dropna(subset=['Description', 'Module'], inplace = True)
zeroData_forprocessing.shape

(4787, 3)

In [17]:
print(zeroData_forprocessing['Description'].apply(type).unique())
print(zeroData_forprocessing['Module'].apply(type).unique())

[<class 'str'>]
[<class 'str'>]

In [197]:
from openpyxl import Workbook
import pandas as pd

# Path to existing Excel file
file_path = r"C:\Users\SHRUTI S\Documents\Repos\Entab Internship\Data Analysis\ZeroData.xlsx"

# Path to new Excel file
output_file_path = r"C:\Users\SHRUTI S\Documents\Repos\Entab Internship\Data Analysis\ZeroDataWithKeywords.xlsx"

# Load data from Excel
data = pd.read_excel(file_path, sheet_name="Data")

# Define keywords
keywords = [
    'Updation', 'Assignment', 'Assigner', 'Reconciliation', 'module wise status',
    'Online Payment', 'Update', 'Paid', 'Promotion', 'Mark assigner', 'Design',
    'SMS', 'DLT', 'Training', 'DEMO', 'Concession', 'Fixed', 'Route Assigner',
    'Demote', 'Chargeback', 'Permission', 'Create', 'Preupgradation', 'Pre Upgradation',
    'Pre-upgradation', 'Upload', 'Entry', 'Fee structure', 'Fine Setting', 'Transfer',
    'Settings', 'Setting', 'collection', 'Adjustment', 'Creation', 'Create',
    'optional subject', 'optional', 'Modification', 'Fee Group', 'Assigning',
    'Tally', 'Tallied', 'visit', 'Data updation', 'Membership', 'Book Entry',
    'Bulk', 'Delete', 'Mapping'
]

# Initialize an empty list to store rows
rows = []

# Initialize an empty DataFrame for keywords (optional)
keywords_df = pd.DataFrame(columns=['Ticket ID', 'Subject', 'Description', 'Module'] + keywords)

# Create a new workbook
book = Workbook()

# Remove the default sheet created by openpyxl
book.remove(book.active)

# Create a sheet for writing the data
sheet = book.create_sheet('KeywordResults')

# Write headers
sheet.append(['Ticket ID', 'Subject', 'Description', 'Module'] + keywords)

# Write data
for idx, row in data.iterrows():
    token_id = row['Ticket ID']
    subject = row['Subject']
    description = str(row['Description'])
    module = row.get('Module', '')  # Get 'Module' column value or default to empty string if not present
    token_row = {'Ticket ID': token_id, 'Subject': subject, 'Description': description, 'Module': module}
    
    # Check for presence of keywords in description (case insensitive) and assign values
    for keyword in keywords:
        if keyword.lower() in description.lower():
            token_row[keyword] = 1
        else:
            token_row[keyword] = 0
    
    # Append current row to list of rows
    rows.append(token_row)

# Write data to the sheet
for row in rows:
    row_data = [row['Ticket ID'], row['Subject'], row['Description'], row['Module']] + [row[keyword] for keyword in keywords]
    sheet.append(row_data)

# Save workbook
book.save(output_file_path)

print(f"Keywords data has been successfully written to '{output_file_path}'")

Keywords data has been successfully written to 'C:\Users\SHRUTI S\Documents\Repos\Entab Internship\Data Analysis\ZeroDataWithKeywords.xlsx'